version: '3.6'

services:
   rajoybot:
     image: elraro/rajoybot
     container_name: rajoybot
     restart: always
     environment:
       TELEGRAM_BOT_TOKEN: XXXX:XXXX
       TELEGRAM_USER_ALIAS: elraro
       WEBHOOK_HOST: 'XXXXXXXXXX'
       WEBHOOK_PORT: '443'
       WEBHOOK_LISTEN: '0.0.0.0'
       WEBHOOK_LISTEN_PORT: 8080
     volumes:
       - rajoydb:/data/db.sqlite
volumes:
    rajoydb:
