version: '3.6'

services:
   rajoybot:
     image: elraro/rajoybot
     container_name: rajoybot
     restart: always
     environment:
       TELEGRAM_BOT_TOKEN: XXXX:XXXX
       TELEGRAM_USER_ALIAS: elraro
     volumes:
       - rajoydb:/data/db.sqlite
volumes:
    rajoydb:
